In [9]:
import pandas as pd 
import numpy as np 
import seaborn as sns 
import matplotlib.pyplot as plt
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.neighbors import NearestNeighbors

## 🖋 Reading Datasets

> ⚠ **`CleanedMovies` Dataset**  i get it from Content-based model by saving the cleaned dataframe to csv file

In [2]:
movies = pd.read_csv("Datasets/CleanedMovies.csv")
ratings = pd.read_csv("Datasets/ratings.csv")

In [3]:
movies.head()

,movieId,title,genres,Year
0,1,Toy Story,Adventure|Animation|Children|Comedy|Fantasy,1995
1,2,Jumanji,Adventure|Children|Fantasy,1995
2,3,Grumpier Old Men,Comedy|Romance,1995
3,4,Waiting to Exhale,Comedy|Drama|Romance,1995
4,5,Father of the Bride Part II,Comedy,1995

In [4]:
ratings.head()

   userId  movieId  rating   timestamp
0       1      296     5.0  1147880044
1       1      306     3.5  1147868817
2       1      307     5.0  1147868828
3       1      665     5.0  1147878820
4       1      899     3.5  1147868510

## ✅ Merging 2 Datasets

In [5]:
df = pd.merge(movies,ratings,on="movieId",how="left")
df

,movieId,title,genres,Year,userId,rating,timestamp
0,1,Toy Story,Adventure|Animation|Children|Comedy|Fantasy,1995,2.0,3.5,1.141416e+09
1,1,Toy Story,Adventure|Animation|Children|Comedy|Fantasy,1995,3.0,4.0,1.439472e+09
2,1,Toy Story,Adventure|Animation|Children|Comedy|Fantasy,1995,4.0,3.0,1.573944e+09
3,1,Toy Story,Adventure|Animation|Children|Comedy|Fantasy,1995,5.0,4.0,8.586259e+08
4,1,Toy Story,Adventure|Animation|Children|Comedy|Fantasy,1995,8.0,4.0,8.904925e+08
...,...,...,...,...,...,...,...
25003466,209157,We,Drama,2018,119571.0,1.5,1.574281e+09
25003467,209159,Window of the Soul,Documentary,2001,115835.0,3.0,1.574281e+09
25003468,209163,Bad Poems,Comedy|Drama,2018,6964.0,4.5,1.574285e+09
25003469,209169,A Girl Thing,(no genres listed),2001,119571.0,3.0,1.574292e+09
25003470,209171,Women of Devil's Island,Action|Adventure|Drama,1962,119571.0,3.0,1.574292e+09

## 👌 Taking random sample of data 

### ⚠ Small hint
> - I made it because my device cannot handle this size of dataset. 
> - If your device can, you can delete this cell
> - you will meet this issue when you making **Pivot Table** (it will use a lot of memory)

In [6]:
sample_data = df.sample(frac=0.001)

## 🟢 Making Pivot Table for our Dataset

In [59]:
Movies_item_matrix = sample_data.pivot_table(values="rating",index="title",columns="userId",aggfunc="mean",fill_value=0)
Movies_item_matrix.head()

userId,6.0,16.0,27.0,36.0,58.0,80.0,86.0,89.0,92.0,95.0,...,162484.0,162486.0,162508.0,162513.0,162516.0,162524.0,162529.0,162533.0,162534.0,162538.0
title,,,,,,,,,,,,,,,,,,,,,
,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
- Nichts ist so wie es scheint,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
/ Weeks Nine / Weeks,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
/ ½,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Again,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [65]:
users_item_matrix = sample_data.pivot_table(values="rating",columns="title",index="userId",aggfunc="mean",fill_value=0)
users_item_matrix.head()

title,,- Nichts ist so wie es scheint,/ Weeks Nine / Weeks,/ ½,Again,Angry Men,Assassins Jûsan-nin no shikaku,Bedroom Bath,Below: Miracle on the Mountain,Blocks,...,th Hour,"th Man, The Sixth Man, The","th Voyage of Sinbad, The","th Warrior, The",x,xXx,xXx: Return of Xander Cage,xXx: State of the Union,¡Three Amigos!,À nos amours
userId,,,,,,,,,,,,,,,,,,,,,
6.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
27.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
36.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
58.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

## 🟢 Get Nearest Moveis by **`K-Nearest Neighbors`** Algorithm

In [74]:
movies_model_knn = NearestNeighbors(metric = "cosine", algorithm = "brute")
movies_model_knn.fit(Movies_item_matrix.values)

NearestNeighbors(algorithm='brute', metric='cosine')

In [75]:
users_model_knn = NearestNeighbors(metric = "cosine", algorithm = "brute")
users_model_knn.fit(users_item_matrix.values)

NearestNeighbors(algorithm='brute', metric='cosine')

In [80]:
def Get_Recommandation(id:int,Pivot_Table:pd.DataFrame,model:NearestNeighbors):


    query_index = id
    distances, indices = model.kneighbors(Pivot_Table.iloc[query_index,:].values.reshape(1, -1), n_neighbors = 10)

    for i in range(0, len(distances.flatten())):
        if i == 0:
            print(f'Recommendations for {Pivot_Table.index[query_index]}:\n')
        else:
            print(f'{i}: {Pivot_Table.index[indices.flatten()[i]]}, with distance of {distances.flatten()[i]}:')

## 📍 Item-Based Collaborative Filtering
Your implementation uses a specific branch called **Item-Item Collaborative Filtering**.

* **The Logic**: Instead of looking for "Users who are like you," the model looks for "Movies that are liked by the same people who liked this movie".
* **The Benefit**: Item-item relationships are generally more stable than user preferences, making the recommendations more reliable over time.

In [81]:
Get_Recommandation(id=1,Pivot_Table=Movies_item_matrix,model=movies_model_knn)

Recommendations for   - Nichts ist so wie es scheint :

1: Zombieland , with distance of 1.0:
2: Zookeeper , with distance of 1.0:
3: Zoolander , with distance of 1.0:
4: Zoolander  , with distance of 1.0:
5: Zootopia , with distance of 1.0:
6: Zorba the Greek Alexis Zorbas , with distance of 1.0:
7: Zorro, the Gay Blade , with distance of 1.0:
8: [REC]² , with distance of 1.0:
9: Youth in Revolt , with distance of 1.0:

## 📍 User-Based Collaborative Filtering

* **The Logic**: Instead of looking for "Movies similar to Toy Story," the model looks for **"Users who have the same taste as you."** If User A and User B both gave 5 stars to the same 10 movies, the model assumes they are "Nearest Neighbors" and recommends movies User B liked that User A hasn't seen yet.
* **The Benefit**: It is excellent for **discovery**. It can recommend a movie from a completely different genre simply because someone with your exact "taste profile" enjoyed it, whereas Item-Based filtering often keeps you within the same category.

In [82]:
Get_Recommandation(id=1,Pivot_Table=users_item_matrix,model=users_model_knn)

Recommendations for 16.0:

1: 143385.0, with distance of 0.0:
2: 141943.0, with distance of 0.0:
3: 136356.0, with distance of 0.0:
4: 55818.0, with distance of 0.0:
5: 19122.0, with distance of 0.0:
6: 16.0, with distance of 0.0:
7: 5253.0, with distance of 0.0:
8: 39133.0, with distance of 0.19999999999999996:
9: 24588.0, with distance of 0.4053646830022669:

---

<h1 align="center">The End of model 😎</h1>


---